[package]
name = "blutgang"
version = "0.1.0"
edition = "2021"
authors = ["makemake <vukasin@gostovic.me>"]
license = "AGPL-3.0-only"
description = "Fast, minimalist weighted round robin load balancing with caching for Ethereum JSOM-RPC calls."
readme = "README.md"
homepage = "https://github.com/rainshowerLabs/sothis"
repository = "https://github.com/rainshowerLabs/sothis"
keywords = ["cli", "ethereum", "foundry", "reth", "revm"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.0"
hyper = { version = "1.0.0-rc.4", features = ["full"] }
http-body-util = "0.1.0-rc.3"
hyper-util = { git = "https://github.com/hyperium/hyper-util.git" }
ratatui = { version = "0.22.0", features = ["all-widgets"] }
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
sled = { version = "0.34.7" }
tokio = { version = "1.28.1", features = ["full"] }
url = "2.4.0"
blake3 = "1.4.1"
