# To use the config file, use the -c/--config option pointing to the path of a config file

# Config for blutgang goes here
[blutgang]
# Clear the cache DB on startup
do_clear = false
# Where to bind blutgang to
address = "localhost:3000"
# Moving average length for the latency
ma_length = 10
# Sort RPCs by latency on startup. Recommended to leave on.
sort_on_startup = true
# Enable health checking
health_check = true
# Acceptable time to wait for a response in ms
ttl = 300
# Time between health checks in ms
health_check_ttl = 12000

# Note: the admin namespace contains volatile functions and
# should not be exposed publicly.
[admin]
# Enable the admin namespace
enabled = true
# Address for the admin RPC
address = "localhost:5715"
# Only allow read-only methods
# Recommended `true` unless you 100% need write methods
readonly = true
# Enable AES encryption of admin namespace requests
# Must be enabled in prod if exposing to the internet
encrypted = false
# 128-bit AES key for the namespace
key = "FILL THIS IN"

# Sled config
# Sled is the database we use for our cache, for more info check their docs
[sled]
# Path to db
db_path = "./blutgang-cache"
# sled mode. Can be HighThroughput/LowSpace
mode = "HighThroughput"
 # Cache size in bytes. Doesn't matter too much as you OS should also be caching.
cache_capacity = 1000000000
# Use zstd compression. Reduces size 60-70%,
# and increases CPU and latency by around 10% for db writes and 2% for reads
compression = false
# Print DB profile when dropped. Doesn't do anything for now.
print_profile = false
# Frequency of flushes in ms
flush_every_ms = 24000

# Add seperate RPCs as TOML tables
# DO NOT name an rpc `blutgang`, `admin`, or `sled`
[llama]
# RPC url
url = "https://eth.llamarpc.com"
# The maximum ammount of time we can use this rpc in a row.
max_consecutive = 5
# Max ammount of querries per second. Doesn't do anything for now.
max_per_second = 0
